/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package computer.security.a1;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       Mainapp mainapp = new Mainapp();
       mainapp.run();
    }
}
